stages:
  - test
  - build
  - deploy

wheel:
  stage: build
  image: python:latest
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python3 -m pip install cibuildwheel
    - python3 -m cibuildwheel --output-dir dist
  artifacts:
    paths:
      - dist

dist:
  stage: build
  image: python:latest
  script:
    - python3 -m pip install build
    - python3 -m build --sdist --outdir dist
  artifacts:
    paths:
      - dist

test:
  stage: test
  image: thekevjames/nox:2022.1.7
  script:
    - apt update
    - apt install -y python3.10 python3.10-dev python3.10-distutils git cmake libboost-all-dev
    - curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
    - mkdir ~/.ssh && ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - git submodule update --init
    - nox

twine:
  stage: deploy
  image: python:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - python3 -m pip install twine
    - echo "$TWINE_USERNAME: $TWINE_PASSWORD"
    - python3 -m twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*
release_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'rostpy release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
